CREATE TABLE IF NOT EXISTS `tb_viticultor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_viticulturer_UNIQUE` (`cpf` ASC) VISIBLE)